# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    http_client:
        scoped_clients:
            dataforseo.api.client:
                base_uri: 'https://api.dataforseo.com'
                auth_basic: '%env(DATAFORSEO_USER)%:%env(DATAFORSEO_PASSWORD)%'
                rate_limiter: 'http_dataforseo_limiter'

    rate_limiter:
        # Don't send more than 30 requests in 1 second
        http_dataforseo_limiter:
            policy: 'token_bucket'
            limit: 30
            rate: { interval: '1 second', amount: 30 }
            lock_factory: null

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
